all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-35-89-103-220.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-34-221-132-156.us-west-2.compute.amazonaws.com
